FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/Yers-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]mv * /путь/к/правильному/репозиторию
                                      mv .git /путь/к/правильному/репозиторию
